# Generated by Django 4.1.1 on 2022-12-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creat_bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('disno', models.SlugField()),
                ('routeno', models.IntegerField()),
                ('busroute', models.URLField()),
                ('bustype', models.CharField(max_length=500)),
                ('bustime', models.IntegerField()),
                ('busstops', models.CharField(max_length=500)),
            ],
        ),
    ]
