# Generated by Django 4.1.1 on 2022-12-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='creat_bus',
            new_name='create_bus',
        ),
    ]
