# Generated by Django 4.1.1 on 2022-12-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0002_rename_creat_bus_create_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_bus',
            name='stop1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='create_bus',
            name='stop2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='create_bus',
            name='stop3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='create_bus',
            name='stop4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='create_bus',
            name='stop5',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
