# Generated by Django 4.2.2 on 2023-07-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0003_create_bus_stop1_create_bus_stop2_create_bus_stop3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.CharField(max_length=100)),
                ('value2', models.CharField(max_length=100)),
            ],
        ),
    ]
