# Generated by Django 4.2.2 on 2023-07-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0004_comparisonmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonmodel',
            name='value3',
            field=models.CharField(default='bypass', max_length=100),
        ),
        migrations.AddField(
            model_name='comparisonmodel',
            name='value4',
            field=models.CharField(default='begampur', max_length=100),
        ),
        migrations.AddField(
            model_name='comparisonmodel',
            name='value5',
            field=models.CharField(default='dindigul', max_length=100),
        ),
        migrations.AlterField(
            model_name='comparisonmodel',
            name='value1',
            field=models.CharField(default='athoor', max_length=100),
        ),
        migrations.AlterField(
            model_name='comparisonmodel',
            name='value2',
            field=models.CharField(default='sempatti', max_length=100),
        ),
    ]
