# Generated by Django 4.2.2 on 2023-07-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0005_comparisonmodel_value3_comparisonmodel_value4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket1', models.IntegerField(blank=True)),
                ('ticket2', models.IntegerField(blank=True)),
                ('ticket3', models.IntegerField(blank=True)),
                ('ticket4', models.IntegerField(blank=True)),
                ('ticket5', models.IntegerField(blank=True)),
                ('ticket6', models.IntegerField(blank=True)),
                ('ticket7', models.IntegerField(blank=True)),
                ('ticket8', models.IntegerField(blank=True)),
                ('ticket9', models.IntegerField(blank=True)),
                ('ticket10', models.IntegerField(blank=True)),
            ],
        ),
    ]
