# Generated by Django 4.2.2 on 2023-07-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0006_tickets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComparisonModel',
        ),
    ]
