# Generated by Django 4.2.2 on 2023-07-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0008_remove_create_bus_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tickets',
        ),
        migrations.AddField(
            model_name='create_bus',
            name='ticket1',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='create_bus',
            name='ticket10',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='create_bus',
            name='ticket2',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='create_bus',
            name='ticket3',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='create_bus',
            name='ticket4',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='create_bus',
            name='ticket5',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='create_bus',
            name='ticket6',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='create_bus',
            name='ticket7',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='create_bus',
            name='ticket8',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='create_bus',
            name='ticket9',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
