# Generated by Django 4.2.2 on 2023-07-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0011_create_bus_accountno_create_bus_bankname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_bus',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
