# Generated by Django 4.2.11 on 2025-02-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0012_create_bus_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bus_name', models.CharField(max_length=100)),
                ('stop1', models.CharField(max_length=100)),
                ('stop2', models.CharField(max_length=100)),
                ('qr_code', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
    ]
