# Generated by Django 4.2.11 on 2025-02-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0013_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='passengers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='qr_code',
            field=models.ImageField(upload_to=''),
        ),
    ]
