# Generated by Django 4.2.11 on 2025-02-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0014_payment_passengers_alter_payment_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_bus',
            name='busname',
            field=models.SlugField(default='enter', max_length=500),
        ),
    ]
