# Generated by Django 4.2.11 on 2025-02-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0015_alter_create_bus_busname'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_bus',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
