# Generated by Django 4.2.11 on 2025-02-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0016_create_bus_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_bus',
            name='accountno',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket1',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket10',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket2',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket3',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket4',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket5',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket6',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket7',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket8',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket9',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
