# Generated by Django 4.2.11 on 2025-02-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0017_alter_create_bus_accountno_alter_create_bus_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_bus',
            name='ticket1',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket10',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket2',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket3',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket4',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket5',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket6',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket7',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket8',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='create_bus',
            name='ticket9',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10),
        ),
    ]
